[application]
# Application name
name = "fact-bot"

# Application icon (for desktop builds)
icon = "assets/favicon.ico"

# Asset directory for desktop builds
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "fact-bot"

# Favicon for web builds
icon = ["assets/favicon.svg"]

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
